micronaut:
  server:
    cors:
      enabled: true
      configurations:
        default:
          allowed-origins:
            - "*"
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers:
            - Content-Type
            - Authorization
            - X-Requested-With
            - Origin
            - Accept
          exposed-headers:
            - Authorization
